name: Build RFlix APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: |
          echo "Runner working!"
          java -version
          ls -la
